// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"armloadtestservice"
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"regexp"
	"slices"
)

// LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServer is a fake server for instances of the armloadtestservice.LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient type.
type LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServer struct {
	// Get is the fake for method LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient.Get
	// HTTP status codes to indicate success: http.StatusOK
	Get func(ctx context.Context, resourceGroupName string, loadTestName string, options *armloadtestservice.LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetOptions) (resp azfake.Responder[armloadtestservice.LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetResponse], errResp azfake.ErrorResponder)

	// Set is the fake for method LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient.Set
	// HTTP status codes to indicate success: http.StatusOK
	Set func(ctx context.Context, resourceGroupName string, loadTestName string, body armloadtestservice.MaxMonthlyVirtualUserHoursLimitRequest, options *armloadtestservice.LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetOptions) (resp azfake.Responder[armloadtestservice.LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetResponse], errResp azfake.ErrorResponder)
}

// NewLoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport creates a new instance of LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport with the provided implementation.
// The returned LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport instance is connected to an instance of armloadtestservice.LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewLoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport(srv *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServer) *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport {
	return &LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport{srv: srv}
}

// LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport connects instances of armloadtestservice.LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient to instances of LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServer.
// Don't use this type directly, use NewLoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport instead.
type LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport struct {
	srv *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServer
}

// Do implements the policy.Transporter interface for LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport.
func (l *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return l.dispatchToMethodFake(req, method)
}

func (l *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if loadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = loadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient.Get":
				res.resp, res.err = l.dispatchGet(req)
			case "LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient.Set":
				res.resp, res.err = l.dispatchSet(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (l *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport) dispatchGet(req *http.Request) (*http.Response, error) {
	if l.srv.Get == nil {
		return nil, &nonRetriableError{errors.New("fake for method Get not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourceGroups/(?P<resourceGroupName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.LoadTestService/loadTests/(?P<loadTestName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/limits/maxMonthlyVirtualUserHours`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 4 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	resourceGroupNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroupName")])
	if err != nil {
		return nil, err
	}
	loadTestNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("loadTestName")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := l.srv.Get(req.Context(), resourceGroupNameParam, loadTestNameParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).MaxMonthlyVirtualUserHoursResource, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (l *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport) dispatchSet(req *http.Request) (*http.Response, error) {
	if l.srv.Set == nil {
		return nil, &nonRetriableError{errors.New("fake for method Set not implemented")}
	}
	const regexStr = `/subscriptions/(?P<subscriptionId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/resourceGroups/(?P<resourceGroupName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/providers/Microsoft\.LoadTestService/loadTests/(?P<loadTestName>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/limits/maxMonthlyVirtualUserHours/set`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 4 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	body, err := server.UnmarshalRequestAsJSON[armloadtestservice.MaxMonthlyVirtualUserHoursLimitRequest](req)
	if err != nil {
		return nil, err
	}
	resourceGroupNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("resourceGroupName")])
	if err != nil {
		return nil, err
	}
	loadTestNameParam, err := url.PathUnescape(matches[regex.SubexpIndex("loadTestName")])
	if err != nil {
		return nil, err
	}
	respr, errRespr := l.srv.Set(req.Context(), resourceGroupNameParam, loadTestNameParam, body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).MaxMonthlyVirtualUserHoursResource, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransport
var loadTestsMaxMonthlyVirtualUserHoursLimitsResourceServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
