// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armloadtestservice

import (
	"context"
	"errors"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"net/url"
	"strings"
)

// LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient contains the methods for the LoadTestsMaxMonthlyVirtualUserHoursLimitsResource
// group.
// Don't use this type directly, use NewLoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient() instead.
//
// Generated from API version 2024-12-01-preview
type LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient struct {
	internal       *arm.Client
	subscriptionID string
}

// NewLoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient creates a new instance of LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient with the specified values.
//   - subscriptionID - The ID of the target subscription. The value must be an UUID.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewLoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient(subscriptionID string, credential azcore.TokenCredential, options *arm.ClientOptions) (*LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient, error) {
	cl, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	client := &LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient{
		subscriptionID: subscriptionID,
		internal:       cl,
	}
	return client, nil
}

// Get - Get the limit of max monthly virtual user hours for the load testing resource.
// If the operation fails it returns an *azcore.ResponseError type.
//   - resourceGroupName - The name of the resource group. The name is case insensitive.
//   - loadTestName - Load Test name
//   - options - LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetOptions contains the optional parameters for the LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient.Get
//     method.
func (client *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient) Get(ctx context.Context, resourceGroupName string, loadTestName string, options *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetOptions) (LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetResponse, error) {
	var err error
	const operationName = "LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient.Get"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.getCreateRequest(ctx, resourceGroupName, loadTestName, options)
	if err != nil {
		return LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetResponse{}, err
	}
	resp, err := client.getHandleResponse(httpResp)
	return resp, err
}

// getCreateRequest creates the Get request.
func (client *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient) getCreateRequest(ctx context.Context, resourceGroupName string, loadTestName string, _ *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.LoadTestService/loadTests/{loadTestName}/limits/maxMonthlyVirtualUserHours"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if resourceGroupName == "" {
		return nil, errors.New("parameter resourceGroupName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{resourceGroupName}", url.PathEscape(resourceGroupName))
	if loadTestName == "" {
		return nil, errors.New("parameter loadTestName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{loadTestName}", url.PathEscape(loadTestName))
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", version20241201Preview)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	return req, nil
}

// getHandleResponse handles the Get response.
func (client *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient) getHandleResponse(resp *http.Response) (LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetResponse, error) {
	result := LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.MaxMonthlyVirtualUserHoursResource); err != nil {
		return LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientGetResponse{}, err
	}
	return result, nil
}

// Set - Set the limit of max monthly virtual user hours for the load testing resource.
// If the operation fails it returns an *azcore.ResponseError type.
//   - resourceGroupName - The name of the resource group. The name is case insensitive.
//   - loadTestName - Load Test name
//   - body - The content of the action request
//   - options - LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetOptions contains the optional parameters for the LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient.Set
//     method.
func (client *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient) Set(ctx context.Context, resourceGroupName string, loadTestName string, body MaxMonthlyVirtualUserHoursLimitRequest, options *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetOptions) (LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetResponse, error) {
	var err error
	const operationName = "LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient.Set"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.setCreateRequest(ctx, resourceGroupName, loadTestName, body, options)
	if err != nil {
		return LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetResponse{}, err
	}
	resp, err := client.setHandleResponse(httpResp)
	return resp, err
}

// setCreateRequest creates the Set request.
func (client *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient) setCreateRequest(ctx context.Context, resourceGroupName string, loadTestName string, body MaxMonthlyVirtualUserHoursLimitRequest, _ *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetOptions) (*policy.Request, error) {
	urlPath := "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.LoadTestService/loadTests/{loadTestName}/limits/maxMonthlyVirtualUserHours/set"
	if client.subscriptionID == "" {
		return nil, errors.New("parameter client.subscriptionID cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{subscriptionId}", url.PathEscape(client.subscriptionID))
	if resourceGroupName == "" {
		return nil, errors.New("parameter resourceGroupName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{resourceGroupName}", url.PathEscape(resourceGroupName))
	if loadTestName == "" {
		return nil, errors.New("parameter loadTestName cannot be empty")
	}
	urlPath = strings.ReplaceAll(urlPath, "{loadTestName}", url.PathEscape(loadTestName))
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.internal.Endpoint(), urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", version20241201Preview)
	req.Raw().URL.RawQuery = strings.ReplaceAll(reqQP.Encode(), "+", "%20")
	req.Raw().Header["Accept"] = []string{"application/json"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, body); err != nil {
		return nil, err
	}
	return req, nil
}

// setHandleResponse handles the Set response.
func (client *LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClient) setHandleResponse(resp *http.Response) (LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetResponse, error) {
	result := LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.MaxMonthlyVirtualUserHoursResource); err != nil {
		return LoadTestsMaxMonthlyVirtualUserHoursLimitsResourceClientSetResponse{}, err
	}
	return result, nil
}
