trigger:
  tags:
  - '*'

parameters:
- name: CheckoutTarget
  type: string
  default: ''

jobs:
  - job: Compliance
    pool:
      name: azsdk-pool-mms-win-2022-general
      image: azsdk-pool-mms-win-2022-1espt
      os: windows

    steps:
      - ${{ if ne(parameters.CheckoutTarget, '') }}:
        - pwsh:
            git clone --no-checkout --filter=tree:0 https://github.com/azure/azure-sdk-assets.git $(Build.SourcesDirectory)
            git checkout ${{ parameters.CheckoutTarget }}
          displayName: Checkout target tag to sources directory
      - ${{ else }}:
        - checkout: self

      - pwsh: |
          ./eng/pipelines/scripts/get-suppressions.ps1 -CredScanSuppressionFolder $(Build.ArtifactStagingDirectory)
        displayName: Get Suppressions File

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
        displayName: Invoke CredScan
        inputs:
          toolVersion: 2.3.12.23
          scanFolder: "$(Build.SourcesDirectory)"
          suppressionsFile: $(Build.ArtifactStagingDirectory)/CredScanSuppressions.json

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@2
        displayName: Analyze Credscan Results
        inputs:
          GdnBreakAllTools: false
          GdnBreakGdnToolCredScan: true
          GdnBreakGdnToolCredScanSeverity: Error