trigger:
  tags:
  - '*'

parameters:
- name: CheckoutTarget
  type: string
  default: ''

jobs:
  - job: Compliance
    pool:
      name: azsdk-pool-mms-win-2022-general
      image: azsdk-pool-mms-win-2022-1espt
      os: windows

    steps:
      - ${{ if ne(parameters.CheckoutTarget, '') }}:
        - pwsh:
            git clone --no-checkout --filter=tree:0 https://github.com/azure/azure-sdk-assets.git $(Build.SourcesDirectory)
            git checkout ${{ parameters.CheckoutTarget }}
          displayName: Checkout target tag to sources directory
      - ${{ else }}:
        - checkout: self

      - pwsh: |
          ./eng/pipelines/scripts/get-suppressions.ps1 -CredScanSuppressionFolder $(Build.ArtifactStagingDirectory)
        displayName: Get Suppressions File

      - template: /eng/pipelines/steps/run-credscan.yml
        parameters:
          ScanFolder: '$(Build.SourcesDirectory)'
          SuppressionsFile: '$(Build.ArtifactStagingDirectory)/CredScanSuppressions.json'