trigger:
  tags:
  - '*'

parameters:
- name: CheckoutTarget
  type: string

jobs:
  - job: Compliance
    pool:
      name: azsdk-pool-mms-win-2022-general
      image: azsdk-pool-mms-win-2022-1espt
      os: windows

    variables:
    - template: /eng/pipelines/variables/image.yml

    steps:
      - ${{ if ne(parameters.CheckoutTarget, '') }}:
        - pwsh:
            git clone --no-checkout --filter=tree:0 https://github.com/azure/azure-sdk-assets.git $(Build.SourcesDirectory)
            git checkout ${{ parameters.CheckoutTarget }}
          displayName: Checkout target tag to sources directory
      - ${{ else }}:
        - checkout: self

      - pwsh: |
          $ErrorActionPreference = 'Stop'

          $req = Invoke-WebRequest https://raw.githubusercontent.com/Azure/azure-sdk-assets/main/eng/CredScanSuppression.json
          $req.RawContent | Out-File (Join-Path -Path $(Agent.BuildDirectory) -ChildPath CredScanSuppression.json)
        displayName: Get Suppressions File

      - template: /eng/pipelines/steps/run-credscan.yml
        parameters:
          ScanFolder: '$(Build.SourcesDirectory)'
          SuppressionsFile: '$(Agent.BuildDirectory)/CredScanSuppression.json'