trigger:
  tags:
    include:
    - '*'

parameters:
- name: CheckoutTarget
  type: string
  default: 'self'

jobs:
  - job: Compliance
    pool:
      name: $(WINDOWSPOOL)
      image: $(WINDOWSVMIMAGE)
      os: windows

    variables:
    - template: /eng/pipelines/variables/image.yml

    steps:
      - ${{ if and(ne(parameters.CheckoutTarget, 'self'), ne(parameters.CheckoutTarget, '')) }}:
        - pwsh:
            git clone --no-checkout --filter=tree:0 https://github.com/azure/azure-sdk-assets.git $(Build.SourcesDirectory)
            git checkout ${{ parameters.CheckoutTarget }}
          displayName: Checkout target tag to sources directory
      - ${{ else }}:
        - pwsh:
            git clone --no-checkout --filter=tree:0 https://github.com/azure/azure-sdk-assets.git $(Build.SourcesDirectory)
            git checkout $(Build.SourceBranch)
          displayName: Checkout Build.SourceVersion to sources directory

      - pwsh: |
          $ErrorActionPreference = 'Stop'

          $destinationFolder = Join-Path -Path "$(Build.SourcesDirectory)" -ChildPath "eng"
          if (-not (Test-Path $destinationFolder)) {
            New-Item -Path $destinationFolder -ItemType Directory
          }
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Azure/azure-sdk-assets/main/eng/CredScanSuppression.json" `
            -OutFile (Join-Path -Path "$destinationFolder" -ChildPath CredScanSuppression.json)
        displayName: Get Suppressions File

      - template: /eng/pipelines/steps/run-credscan.yml
        parameters:
          Tag: ${{ parameters.CheckoutTarget }}
          ScanFolder: '$(Build.SourcesDirectory)'
          SuppressionsFile: '$(Build.SourcesDirectory)/eng/CredScanSuppression.json'