parameters:
  - name: Matrix
    type: string
  - name: TestTimeoutInMinutes
    type: number
    default: 60
jobs:
  - job:
    displayName: 'CredScan'
    condition: |
      and(
        succeededOrFailed(),
        ne(${{ parameters.Matrix }}, '{}')
      )
    timeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}

    strategy:
      matrix: $[ ${{ parameters.Matrix }} ]

    pool:
      name: azsdk-pool-mms-win-2022-general
      image: azsdk-pool-mms-win-2022-1espt
      os: linux

    variables:
      CloneFolder: '$(Build.SourcesDirectory)/tag_clone'

    steps:
      - checkout: none

      - pwsh: |
          ./eng/pipelines/scripts/get-suppressions.ps1 -CredScanSuppressionFolder $(Build.ArtifactStagingDirectory)
        displayName: Get Suppressions File

      - pwsh:
          git clone --no-checkout --filter=tree:0 https://github.com/azure/azure-sdk-assets.git .
          git checkout $(Tag)
        displayName: Checkout $(Tag)
        workingDirectory: $(CloneFolder)

      - template: /eng/pipelines/steps/run-credscan.yml
        parameters:
          ScanFolder: '$(CloneFolder)'
          SuppressionsFile: '$(Build.ArtifactStagingDirectory)/CredScanSuppressions.json'