parameters:
  - name: Matrix
    type: string
  - name: TestTimeoutInMinutes
    type: number
    default: 60
  - name: CloudConfig
    type: object
    default: {}
  - name: UsePlatformContainer
    type: boolean
    default: false
  - name: DependsOn
    type: object
    default: []
jobs:
  - job:
    displayName: 'CredScan'
    condition: |
      and(
        succeededOrFailed(),
        ne(${{ parameters.Matrix }}, '{}')
      )
    timeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}

    strategy:
      matrix: $[ ${{ parameters.Matrix }} ]
      maxParallel: 5

    dependsOn:
      - ${{ parameters.DependsOn }}

    pool:
      name: $(WINDOWSPOOL)
      image: $(WINDOWSVMIMAGE)
      os: linux

    variables:
      CloneFolder: '$(Build.SourcesDirectory)/tag_clone'

    steps:
      - checkout: none

      - pwsh: |
          $ErrorActionPreference = 'Stop'

          $req = Invoke-WebRequest https://raw.githubusercontent.com/Azure/azure-sdk-assets/main/eng/CredScanSuppression.json
          $req.RawContent | Out-File (Join-Path -Path $(Build.ArtifactStagingDirectory) -ChildPath CredScanSuppression.json)
        displayName: Get Suppressions File

      - pwsh: |
          New-Item -ItemType Directory -Path $(CloneFolder) -Force
        displayName: Create Clone Folder

      - pwsh: |
          git clone --no-checkout --filter=tree:0 https://github.com/azure/azure-sdk-assets.git .
          git checkout $(Tag)
        displayName: Checkout $(Tag)
        workingDirectory: $(CloneFolder)

      - template: /eng/pipelines/steps/run-credscan.yml
        parameters:
          ScanFolder: '$(CloneFolder)'
          SuppressionsFile: '$(Build.ArtifactStagingDirectory)/CredScanSuppression.json'