parameters:
  - name: Matrix
    type: string
  - name: TestTimeoutInMinutes
    type: number
    default: 60
  - name: CloudConfig
    type: object
    default: {}
  - name: UsePlatformContainer
    type: boolean
    default: false
  - name: DependsOn
    type: object
    default: []
jobs:
  - job:
    displayName: 'CredScan'
    condition: |
      and(
        succeededOrFailed(),
        ne(${{ parameters.Matrix }}, '{}'),
        ne(${{ parameters.Matrix }}, "dependencies.generate_job_matrix.outputs['generate_vm_job_matrix_tag_matrix.matrix']")
      )
    timeoutInMinutes: ${{ parameters.TestTimeoutInMinutes }}

    strategy:
      matrix: $[ ${{ parameters.Matrix }} ]
      maxParallel: 5

    dependsOn:
      - ${{ parameters.DependsOn }}

    pool:
      name: $(WINDOWSPOOL)
      image: $(WINDOWSVMIMAGE)
      os: linux

    steps:
      - checkout: none

      - pwsh: |
          Write-Host "${{ parameters.Matrix }}"

      - pwsh: |
          $ErrorActionPreference = 'Stop'

          $req = Invoke-WebRequest https://raw.githubusercontent.com/Azure/azure-sdk-assets/main/eng/CredScanSuppression.json
          $req.RawContent | Out-File (Join-Path -Path $(Agent.BuildDirectory) -ChildPath CredScanSuppression.json)
        displayName: Get Suppressions File

      - pwsh: |
          git clone --no-checkout --filter=tree:0 https://github.com/azure/azure-sdk-assets.git .
          git checkout $(Tag)
        displayName: Checkout $(Tag)

      - template: /eng/pipelines/steps/run-credscan.yml
        parameters:
          Tag: $(Tag)
          ScanFolder: '$(Build.SourcesDirectory)'
          SuppressionsFile: '$(Agent.BuildDirectory)/CredScanSuppression.json'
